Add Latin script for Manchu (mnc-latn)
wikimedia/language-data pull request #263
Opened 2022-11-09 09:51 UTC by nikkiwd

Manchu (mnc) should be added to Names.php [1] but the translations are a mixture of Latin and Mongolian scripts and need to be split [2]. For the autonym, see the existing translations [3] and the main page of the Manchu Wikipedia in the Incubator [4].

[1] https://phabricator.wikimedia.org/T284043
[2] https://phabricator.wikimedia.org/T318496
[3] https://translatewiki.net/w/i.php?search=%22manju+gisun%22&ns8=1&ns1206=1
[4] https://incubator.wikimedia.org/wiki/Wp/mnc/%E1%A1%A0%E1%A0%B5%E1%A1%A0%E1%A1%B3_%E1%A0%A0%E1%A1%B6%E1%A0%A0%E1%A1%A5%E1%A0%A0

2024-01-12 06:35 UTC, winstonsung requested changes

2024-01-12 06:35 UTC, winstonsung commented on data/langdb.yaml
> +  mnc-latn: [Latn, [AS], Manju gisun]
"M" should be lowercase?

2024-01-12 06:35 UTC, winstonsung commented on data/language-data.json
> +            "Manju gisun"
Same here.

2024-01-12 06:43 UTC, nikkiwd commented on data/language-data.json
> +            "Manju gisun"
This is automatically generated from langdb.yaml.

2024-01-12 07:02 UTC, winstonsung commented on data/langdb.yaml
> +  mnc-latn: [Latn, [AS], Manju gisun]
https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/core/+/ee48e9f/includes/languages/data/Names.php#339

2024-01-12 07:21 UTC, nikkiwd commented on data/langdb.yaml
> +  mnc-latn: [Latn, [AS], Manju gisun]
As far as I can tell, it's a matter of preference. Some people never use capital letters, some people capitalise proper nouns, e.g. the very first line of the Incubator page I linked in the commit message is "ubade latino(Möllendorff) hergen -i ubaliyambuha Manju gisun -i Uikipidiya -i ujui afaha de dosireo." (which isn't someone using English-style capitalisation, the beginning of the sentence isn't capitalised, neither is the word for "Latin"). The autonym on Translatewiki was also capitalised until Amir changed it.

Is one option actually better than the other? I don't know, it's easier to lowercase everything automatically than it is to detect which words are proper nouns though.

2024-01-12 08:56 UTC, winstonsung commented on data/langdb.yaml
> +  mnc-latn: [Latn, [AS], Manju gisun]
> https://t.me/wikipedia_zh_ac/112283
> https://t.me/wikipedia_zh_ac/112284
> https://t.me/wikipedia_zh_ac/112291
> https://en.wikisource.org/wiki/A_Manchu_Grammar
> https://t.me/wikipedia_zh_ac/112292
> https://t.me/wikipedia_zh_ac/112293
> https://t.me/wikipedia_zh_ac/112295
> https://t.me/wikipedia_zh_ac/112296

> There are only transcriptions, no structured grammer for Manchu in Latin script
> Paul Georg von Möllendorff used all-lowercase in _A Manchu Grammar with Analysed Texts_

One Manchu user:
> "Suggested: it's better to use capitalization for proper nouns, but there's no actual standard for either lowercase or uppercase"
> "Both are acceptable at the moment, just need the community consensus to decide it."

2024-01-12 09:03 UTC, winstonsung commented on data/langdb.yaml
> +  mnc-latn: [Latn, [AS], Manju gisun]
Looks like it's fine to use uppercase, just make sure the consistency.

2024-03-07 18:48 UTC, winstonsung commented
(CR+1)
(rebase needed)

2024-04-17 02:55 UTC, amire80 approved these changes

2024-04-17 02:55 UTC, merged