Sort YAML alphabetically
wikimedia/language-data pull request #303
Opened 2023-07-13 11:34 UTC by amire80

Also add an automatic test for that.

2023-07-13 13:53 UTC, amire80 commented
<s>Don't merge yet. I've added a test to check that the YAML keys are sorted, and the test identifies if they aren't, but doesn't actually fail in that case.</s>

2023-07-16 12:58 UTC, amire80 commented
I think it's correct now. Can be reviewed.

2023-07-17 08:21 UTC, Abijeet requested changes

2023-07-17 08:21 UTC, Abijeet commented on composer.json
> +		"yaml-sort-check": "composer require mhujer/yaml-sort-checker; yaml-sort-checker",
`composer require mhujer/yaml-sort-checker` library can be added to this section: https://github.com/wikimedia/language-data/blob/master/composer.json#L36

2023-07-17 08:27 UTC, amire80 commented on composer.json
> +		"yaml-sort-check": "composer require mhujer/yaml-sort-checker; yaml-sort-checker",
That's what I did initially. The reason I switched to this hack is that the library I use for testing YAML sorting is incompatible with PHP < 8.1, and require in composer.json applies to all PHP versions.

2023-07-17 08:35 UTC, Abijeet commented on composer.json
> +		"yaml-sort-check": "composer require mhujer/yaml-sort-checker; yaml-sort-checker",
OK. Can you add a comment in `.github/workflows/php.yml` regarding that?

2023-07-17 08:40 UTC, amire80 commented on composer.json
> +		"yaml-sort-check": "composer require mhujer/yaml-sort-checker; yaml-sort-checker",
Done.

2023-07-17 08:48 UTC, Abijeet approved these changes

2023-07-17 08:52 UTC, merged