Change hak configuration in line with core MediaWiki
wikimedia/language-data pull request #371
Opened 2024-07-22 15:51 UTC by amire80

Core MediaWiki now uses three separate codes for
three scripts, and one code that includes two names. See https://gerrit.wikimedia.org/r/c/mediawiki/core/+/876411

2024-07-22 15:56 UTC, winstonsung requested changes

2024-07-22 15:56 UTC, winstonsung commented on data/langdb.yaml
> +  hak: [Hant, [AS], 客家語（繁體） / Hak-kâ-ngî]
"（繁體）", which means "(Traditional (Han) script)", should not be included here.

2024-07-22 15:56 UTC, winstonsung commented on data/langdb.yaml
> -  hak: [Latn, [AS], Hak-kâ-fa]
Should still keep `Latn` unless the translation of "Main Page" changed on Wikipedia-hak and other `hak` wikis.

2024-07-22 15:58 UTC, amire80 commented on data/langdb.yaml
> +  hak: [Hant, [AS], 客家語（繁體） / Hak-kâ-ngî]
Oh, of course. Thanks!

2024-07-22 16:07 UTC, amire80 commented on data/langdb.yaml
> -  hak: [Latn, [AS], Hak-kâ-fa]
It's a weird balance: On one hand, the most important downstream client of language-data is MediaWiki. On the other hand, I don't want to be too dependent on MediaWiki or on the main page of a specific Wikimedia project. If the main script for this language is Chinese in real life, it should probably be Hant here.

In practical terms, for ULS on Wikimedia projects, it means that it will be grouped alphabetically with the Chineses-script entries and not with the Latin-script entries, but this grouping is just eye candy. Most people don't actually scroll through the list, and use the search box instead. This language will be findable using the search box with both scripts.

2024-07-22 16:21 UTC, winstonsung commented on data/langdb.yaml
> -  hak: [Latn, [AS], Hak-kâ-fa]
Then I guess using `Hant` would probably be fine.

2024-07-22 16:22 UTC, winstonsung approved these changes

2024-07-22 16:29 UTC, winstonsung commented on data/langdb.yaml
> -  hak: [Latn, [AS], Hak-kâ-fa]
(For consistency, you might also want to use `Hant` for `cdo` and `nan` .)

2024-08-05 09:36 UTC, srish approved these changes
Looks good to me.

2024-08-05 09:37 UTC, merged